language: java
#jdk:
#  - oraclejdk8

before_install:
  # get latest JVM repo
  - sudo echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/webupd8team-java.list
  - sudo echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list.d/webupd8team-java.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
  # make sure everything's up to date
  - sudo apt-get update -qq

install:
  - sudo apt-get install --no-install-recommends oracle-java8-installer
  - sudo apt-get install oracle-java8-set-default


script:
  - jdk_switcher use oraclejdk8
  - mvn test
